# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-20 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20180220_0520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='timestamp',
        ),
    ]
